### ISSUE TITLE
JsReportBinaryException error

### ISSUE THREAD

**Issue by kimbaudi** [jsreport/jsreport-dotnet-example-webapp#10]
Hi, I am getting the following error when I checkout this repo and build/run on Visual Studio 2019:

![image](https://user-images.githubusercontent.com/1864092/156430535-a5321e12-4b8a-40d6-af3e-554272852799.png)

```shell
JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 24240)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). spawn UNKNOWN (1). caused by error (2):-> stackError: at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19) at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:256:14 at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError: at Client.render (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async startRender (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:319:24) at async D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:226:22 at async Commander.executeCommand (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commander.js:242:22)Remote stack: Error: at ChildProcess.spawn (internal/child_process.js:407:11) at Object.spawn (child_process.js:548:9) at Object.childProcess.spawn (pkg/prelude/bootstrap.js:1496:27) at Launcher.launch (D:\snapshot\jsreport\node_modules\puppeteer\lib\Launcher.js:132:40) at async getBrowser (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\dedicatedProcessStrategy.js:13:21) at async D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\conversion.js:4:19 at async execute (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\dedicatedProcessStrategy.js:10:22) at async Object.execute (D:\snapshot\jsreport\node_modules\jsreport-chrome-pdf\lib\chrome.js:69:20) at async D:\snapshot\jsreport\node_modules\jsreport-core\lib\render\render.js:149:5
```

**Comment by kimbaudi** [comment]
Hi, I updated `jsreport.Local` and `jsreport.Binary` NuGet packages to latest and I no longer get the error.

![image](https://user-images.githubusercontent.com/1864092/156431226-1777b22b-eea8-4d74-b3de-27a1773d2f40.png)
![image](https://user-images.githubusercontent.com/1864092/156431522-6a7bfeb3-131e-46eb-b8c8-01795d825c2c.png)
