### ISSUE TITLE
Jsreport.Local.JsReportBinaryException:

### ISSUE THREAD

**Issue by huxaiphaer** [jsreport/jsreport-dotnet-example-webapp#5]
I have cloned this repository and I tried to run it on mac but I got the following exception, and on top of that I added the IOS NuGet `dotnet add package jsreport.Binary.OSX --version 2.5.0` what could be the reason for causing it?  

```
Jsreport.Local.JsReportBinaryException: Error rendering report: 
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
   at jsreport.AspNetCore.JsReportMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by huxaiphaer** [comment]
open

**Comment by pofider** [comment]
Please locate jsreport binary in temp\dotnet\binary-default-2.5.0.0\jsreport.exe and render something in commandline using

```
jsreport render --template.content=test.html --template.engine=none --template.recipe=chrome-pdf --out=out.pdf
```

Let me know if that worked.

**Comment by huxaiphaer** [comment]
Actually, I made it work by making `jsreport` know that is using a mac with the following code in the `Start.cs file`, but thanks a lot for the help :

```
  services.AddJsReport(new LocalReporting()
                .UseBinary(RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                    ? JsReportBinary.GetBinary()
                    : jsreport.Binary.OSX.JsReportBinary.GetBinary())
                .AsUtility()

```
